name: Test

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Print a message
        run: echo "Hello world!"

      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: dataorchestration/helm-ondc-buyer-app-chart
          token: ${{ secrets.PAT_TOKEN }}
          path: repo-b # This will clone Repo B into a folder named 'repo-b'

       - name: Fetch all branches
        run: |
          cd repo-b
          git fetch --all

      - name: Check out or create the test-cicd branch
        run: |
          cd repo-b
          git checkout test-cicd || git checkout -b test-cicd

      - name: Make Changes in Repo B
        run: |
          cd repo-b
          echo "Hello from Repo A!" >> newfile.txt

      - name: Commit and Push changes to Repo B
        run: |
          cd repo-b
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update from biap-client-node-js"
          git push origin test-cicd
