 name: Deployment

on:
  push:
    branches: ["master"]

# aws env from secrets
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-south-1
  CONFIG_FILE: services/config_maps/node-js-client-version-config.yaml
  IMAGE: public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app:clientsvcv

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout client Node repo
        uses: actions/checkout@v3

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(cat VERSION)"

      - name: Determine next version
        id: next_version
        run: |
          current_version=$(cat VERSION)
          IFS='.' read -r -a version_parts <<< "$current_version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="${version_parts[2]}"

          patch=$((patch + 1))

          next_version="$major.$minor.$patch"
          echo "updated version: $next_version"
          echo "::set-output name=next_version::$next_version"  

      - name: Check if tags exist
        id: check_tags
        run: |
          if [ -z "$(git tag)" ]; then
            echo "No tags found in the repository."
            exit 0
          fi

   

      - name: Update version file
        run: echo "${{ steps.next_version.outputs.next_version }}" > VERSION
        
      - name: Commit updated version file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add VERSION
          git commit -m "Update version to ${{ steps.next_version.outputs.next_version }}"  || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
                    
      - name: Create Git tag       
        run: |
          TAG_EXISTS=$(git tag --contains HEAD)
          if [ -n "$TAG_EXISTS" ]; then
            echo "Tag already exists for this commit: $TAG_EXISTS"
          else           
            git tag "v${{ steps.next_version.outputs.next_version }}"
            git push origin "v${{ steps.next_version.outputs.next_version }}"
          fi
                          
      - name: Checkout helm chart repo
        uses: actions/checkout@v3
        with:
          repository: dataorchestration/helm-ondc-buyer-app-chart
          token: ${{ secrets.PAT_TOKEN }}
          path: repo-helm-chart # This will clone Repo B into a folder named 'repo-helm-chart'

      - name: Fetch all branches
        run: |
          cd repo-helm-chart
          git fetch --all

      - name: Check out or create the test-cicd branch
        run: |
          cd repo-helm-chart
          git checkout test-cicd || git checkout -b test-cicd

      - name: Make Changes in repo-helm-chart
        run: |
          cd repo-helm-chart
          cat <<EOF > ${{ env.CONFIG_FILE }}
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: node-js-client-version-config
            namespace: ondc-prod-prod
          data:
            image_tag: ${{ env.IMAGE }}${{ steps.next_version.outputs.next_version }}
          EOF

      - name: Commit and Push changes to repo-helm-chart
        run: |
          cd repo-helm-chart
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update config from biap-client-node-js" || echo "No changes to commit"
          git push origin test-cicd || echo "No changes to push"

      - name: Set up AWS CLI with ecr-pusher profile
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }} --profile ecr-pusher
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }} --profile ecr-pusher
          aws configure set region ${{ env.AWS_DEFAULT_REGION }} --profile ecr-pusher

      - name: docker login to ECR
        run: AWS_PROFILE=ecr-pusher aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l6b3l7s4

      - name: build image
        run: docker build --platform linux/x86_64 -f Dockerfile -t  ${{ env.IMAGE }}${{ steps.next_version.outputs.next_version }} .

      - name: push image to ECR
        run: docker push  ${{ env.IMAGE }}${{ steps.next_version.outputs.next_version }}


      # - name: configure kubectl
      #   run: aws eks --region ap-south-1 update-kubeconfig --name ondc-prod-prod-eks-cluster

      # - name: Apply updated config
      #   run: |
      #     cd repo-helm-chart
      #     cat services/config_maps/node-js-client-version-config.yaml
      #     kubectl apply -f services/config_maps/node-js-client-version-config.yaml

      # - name: Install Helm
      #   uses: azure/setup-helm@v3
      #   with:
      #     version: 'latest'

      # - name: Helm Upgrade
      #   run: |
      #     cd repo-helm-chart/services
      #     helm upgrade ondc-buyer-app-release . -f values.yaml --namespace ondc-prod-prod        
