name: Test

on:
  push:
    branches: ["master"]

# aws env from secrets
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-south-1
  CONFIG_FILE: services/config_maps/node-js-client-version-config.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout client Node repo
        uses: actions/checkout@v3

      - name: Checkout helm chart repo
        uses: actions/checkout@v3
        with:
          repository: dataorchestration/helm-ondc-buyer-app-chart
          token: ${{ secrets.PAT_TOKEN }}
          path: repo-helm-chart # This will clone Repo B into a folder named 'repo-helm-chart'

      - name: Fetch all branches
        run: |
          cd repo-helm-chart
          git fetch --all

      - name: Check out or create the test-cicd branch
        run: |
          cd repo-helm-chart
          git checkout test-cicd || git checkout -b test-cicd

      - name: Make Changes in repo-helm-chart
        run: |
          cd repo-helm-chart
          cat <<EOF > ${{ env.CONFIG_FILE }}
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: node-js-client-version-config
            namespace: ondc-prod-prod
          data:
            image_tag: "public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app:clientsvcv1.2"
          EOF

      - name: Commit and Push changes to reoo-helm-chart
        run: |
          cd repo-helm-chart
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update config from biap-client-node-js"
          git push origin test-cicd

      - name: configure kubectl
        run: aws eks --region ap-south-1 update-kubeconfig --name ondc-prod-prod-eks-cluster

      - name: Apply updated config
        run: |
          cd repo-helm-chart
          cat services/config_maps/node-js-client-version-config.yaml
          kubectl apply -f services/config_maps/node-js-client-version-config.yaml
